# Generated by Django 5.1.4 on 2025-01-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_userprofile_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='cart_users', to='product.product'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='wishlist_users', to='product.product'),
        ),
    ]
