# Generated by Django 5.1.4 on 2025-01-21 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_userprofile_cart_alter_userprofile_wishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
